uab_pocris:
    
    resource: "@UabPocrisBundle/Resources/config/routing.yml"
    
    prefix:   /pocris


uab_florin:
    resource: "@UabFlorinBundle/Resources/config/routing.yml"
    prefix:   /florin

uab_magerusan:
    resource: "@UabMagerusanBundle/Resources/config/routing.yml"
    prefix:   /magerusan

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

uab_marius:
    resource: "@UabBreazBundle/Resources/config/routing.yml"
    prefix:   /marius

uab_solymosi:
    resource: "@UabSolymosiBundle/Resources/config/routing.yml"
    prefix:   /solymosi
