student_index:
    path:     /
    defaults: { _controller: "UabFlorinBundle:Student:index" }
    methods:  GET

student_show:
    path:     /{id}/show
    defaults: { _controller: "UabFlorinBundle:Student:show" }
    methods:  GET

student_new:
    path:     /new
    defaults: { _controller: "UabFlorinBundle:Student:new" }
    methods:  [GET, POST]

student_edit:
    path:     /{id}/edit
    defaults: { _controller: "UabFlorinBundle:Student:edit" }
    methods:  [GET, POST]

student_delete:
    path:     /{id}/delete
    defaults: { _controller: "UabFlorinBundle:Student:delete" }
    methods:  DELETE
