uab_florin_universitate:
    resource: "@UabFlorinBundle/Resources/config/routing/universitate.yml"
    prefix:   /universitate

uab_florin_homepage:
    path: /
    defaults: { _controller: UabFlorinBundle:Default:index }
